module.exports = {
  ROOM_STATUS: {
    AVAILABLE: 'AVAILABLE',
    OCCUPIED: 'OCCUPIED',
    DIRTY: 'DIRTY',
    MAINTENANCE: 'MAINTENANCE',
    RESERVED: 'RESERVED'
  },
  RESERVATION_STATUS: {
    PENDING: 'PENDING',
    CONFIRMED: 'CONFIRMED',
    CHECKED_IN: 'CHECKED_IN',
    CHECKED_OUT: 'CHECKED_OUT',
    CANCELLED: 'CANCELLED'
  },
  ROLES: {
    ADMIN: 'ADMIN',
    FRONT_OFFICE: 'FRONT_OFFICE',
    HOUSEKEEPING: 'HOUSEKEEPING',
    FINANCE: 'FINANCE'
  }
};
