// server/config/constants.js

/**
 * Uygulama sabitleri
 * Tüm sabit değerleri merkezi olarak yönetir
 */

const CONSTANTS = {
  // Departmanlar
  DEPARTMENTS: {
    FRONTOFFICE: 'FRONTOFFICE',
    HOUSEKEEPING: 'HOUSEKEEPING',
    FINANCE: 'FINANCE',
    ADMIN: 'ADMIN',
  },

  // Roller
  ROLES: {
    ADMIN: 'ADMIN',
    MANAGER: 'MANAGER',
    SUPERVISOR: 'SUPERVISOR',
    STAFF: 'STAFF',
    DIRECTOR: 'DIRECTOR',
  },

  // Rol-Departman Eşlemeleri
  ROLE_DEPARTMENT_MAP: {
    ADMIN: ['FRONTOFFICE', 'HOUSEKEEPING', 'FINANCE', 'ADMIN'],
    DIRECTOR: ['FRONTOFFICE', 'HOUSEKEEPING', 'FINANCE'],
    MANAGER: ['FRONTOFFICE', 'HOUSEKEEPING', 'FINANCE'],
    SUPERVISOR: ['FRONTOFFICE', 'HOUSEKEEPING', 'FINANCE'],
    STAFF: ['FRONTOFFICE', 'HOUSEKEEPING', 'FINANCE'],
  },

  // Oda Durumları
  ROOM_STATUS: {
    AVAILABLE: 'AVAILABLE',
    OCCUPIED: 'OCCUPIED',
    MAINTENANCE: 'MAINTENANCE',
    CLEANING: 'CLEANING',
    BLOCKED: 'BLOCKED',
    OUT_OF_SERVICE: 'OUT_OF_SERVICE',
  },

  // Oda Temizlik Durumları
  ROOM_CONDITION: {
    CLEAN: 'CLEAN',
    DIRTY: 'DIRTY',
    DAMAGED: 'DAMAGED',
    INSPECTED: 'INSPECTED',
  },

  // Oda Tipleri
  ROOM_TYPES: {
    SINGLE: 'SINGLE',
    DOUBLE: 'DOUBLE',
    TWIN: 'TWIN',
    TRIPLE: 'TRIPLE',
    SUITE: 'SUITE',
    DELUXE: 'DELUXE',
    PRESIDENTIAL: 'PRESIDENTIAL',
    FAMILY: 'FAMILY',
    STUDIO: 'STUDIO',
  },

  // Rezervasyon Durumları
  RESERVATION_STATUS: {
    PENDING: 'PENDING',
    CONFIRMED: 'CONFIRMED',
    CHECKED_IN: 'CHECKED_IN',
    CHECKED_OUT: 'CHECKED_OUT',
    CANCELLED: 'CANCELLED',
    NO_SHOW: 'NO_SHOW',
    SUSPENDED: 'SUSPENDED',
    WAITLIST: 'WAITLIST',
  },

  // Ödeme Durumları
  PAYMENT_STATUS: {
    PENDING: 'PENDING',
    AUTHORIZED: 'AUTHORIZED',
    CAPTURED: 'CAPTURED',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
    REFUNDED: 'REFUNDED',
    PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED',
    CANCELLED: 'CANCELLED',
  },

  // Ödeme Yöntemleri
  PAYMENT_METHODS: {
    CREDIT_CARD: 'CREDIT_CARD',
    DEBIT_CARD: 'DEBIT_CARD',
    CASH: 'CASH',
    BANK_TRANSFER: 'BANK_TRANSFER',
    CHECK: 'CHECK',
    MOBILE_PAYMENT: 'MOBILE_PAYMENT',
    DIGITAL_WALLET: 'DIGITAL_WALLET',
    POINTS: 'POINTS',
  },

  // Ödeme Türleri
  PAYMENT_TYPE: {
    FULL: 'FULL',
    PARTIAL: 'PARTIAL',
    DEPOSIT: 'DEPOSIT',
    FINAL: 'FINAL',
  },

  // Temizlik Görev Durumları
  HOUSEKEEPING_STATUS: {
    ASSIGNED: 'ASSIGNED',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
    INSPECTED: 'INSPECTED',
    REJECTED: 'REJECTED',
    PENDING_INSPECTION: 'PENDING_INSPECTION',
  },

  // Bakım Taleplerinin Önceliği
  MAINTENANCE_PRIORITY: {
    URGENT: 'URGENT',
    HIGH: 'HIGH',
    MEDIUM: 'MEDIUM',
    LOW: 'LOW',
  },

  // Bakım Talep Durumları
  MAINTENANCE_STATUS: {
    REPORTED: 'REPORTED',
    ASSIGNED: 'ASSIGNED',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
    CLOSED: 'CLOSED',
  },

  // Envanter Kategorileri
  INVENTORY_CATEGORIES: {
    LINENS: 'LINENS',
    TOILETRIES: 'TOILETRIES',
    SUPPLIES: 'SUPPLIES',
    FURNITURE: 'FURNITURE',
    EQUIPMENT: 'EQUIPMENT',
    MINI_BAR: 'MINI_BAR',
    AMENITIES: 'AMENITIES',
  },

  // Misafir Türleri
  GUEST_TYPE: {
    INDIVIDUAL: 'INDIVIDUAL',
    CORPORATE: 'CORPORATE',
    TRAVEL_AGENCY: 'TRAVEL_AGENCY',
    GROUP: 'GROUP',
    LOYALTY: 'LOYALTY',
  },

  // Misafir Durumları
  GUEST_STATUS: {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    BLACKLISTED: 'BLACKLISTED',
    VIP: 'VIP',
    REGULAR: 'REGULAR',
